version: '3'

services: 

  mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=crud
      - MYSQL_USER=alif
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306

  app:
    image: spring-boot
    depends_on:
      - mysqldb
    ports:
      - 8080:8080
    links:
      - mysqldb
    environment:
        - spring.datasource.url=jdbc:mysql://mysqldb:3306/crud
        - spring.datasource.username=alif
        - spring.datasource.password=password